.travis.yml
ci/install-ldns.sh
ci/install-libuv.sh

This change set adds configuration for Travis CI.
The build is enabled for Linux and macOS. The provided Linux build environment is relatively old so we have to build libuv and ldns from sources.

Add Travis for CI

---

.gitignore
.travis.yml
CMakeLists.txt
README.md
flame/config.h
flame/main.cpp
flame/metrics.h
flame/query.cpp
flame/query.h
flame/tcpsession.cpp
flame/tcpsession.h
flame/tcptlssession.cpp
flame/tcptlssession.h
flame/trafgen.cpp
flame/trafgen.h

I've dug out some patches we did a while back to add TCP/TLS support (i.e. DoT) to Flamethrower, and updated them to the current tree.
I also added some fixes for warnings when building using Debian Unstable's GCC 8.2.0.

Add support for flaming over DoT

---

README.md
flame/main.cpp
flame/trafgen.cpp
flame/trafgen.h

The TARGET command line option now supports comma separated list, or the special keyword "file" which, combined with --targets option, allows reading the list from a file.

Add ability to send to multiple targets at once

---

README.md

Earlier versions of CMake don't support CMAKE_CXX_STANDARD 17 and fail
with:
target requires the language dialect “CXX17” (with compiler extensions),
but CMake does not know the compile flags to use to enable it

README: update CMake dependency to 3.8

---

CMakeLists.txt

flame does not compile without it, since main.cpp is using uv_refs but
does not explicitly reference it itself.
Tried on Fedora 29.
```
$ rpm -q libuv ldns gcc cmake
libuv-1.30.1-1.fc29.x86_64
ldns-1.7.0-21.fc29.x86_64
gcc-8.3.1-2.fc29.x86_64
cmake-3.14.5-1.fc29.x86_64
```
Compilation failed with:
```
/usr/bin/cmake -E cmake_link_script CMakeFiles/flame.dir/link.txt --verbose=1
[100%] Linking CXX executable tests
/usr/bin/cmake -E cmake_link_script CMakeFiles/tests.dir/link.txt --verbose=1
/usr/lib64/ccache/c++  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic …
```

Flame requires explicit uv link

---

CMakeLists.txt

CMake provides easy way for installing built binaries.
Add make install target with DESTDIR support. Support lib64
install suffix.
Signed-off-by: Petr Menšík <pemensik@redhat.com>

Provide install target

---

CMakeLists.txt
flame/metrics.cpp
flame/metrics.h
flame/version.h

- fix bug in calculation of max `total_response_max_ms`
- remove unused `MetricsMgr` reference to fix compile warning
- add `period_number` to json output

Metrics fixes and improvements

---

CMakeLists.txt
cmake/sanitizer.cmake
flame/query.cpp
flame/query.h

The file generator now supports ipv4/ipv6 ecs, like so:
```
[elindsey@worktop:~/code/flamethrower/build]
$ cat ../ecstest.txt 
google.com A 2001:db8:cafe:c000::/50
google.com A 192.0.100.0/24
[elindsey@worktop:~/code/flamethrower/build]
$ ./flame -v 5 -f ../ecstest.txt 216.239.36.10
```
Some pcaps:

add client-subnet support to the file generator

---

CMakeLists.txt
README.md
flame/main.cpp
flame/trafgen.cpp
flame/trafgen.h
flame/version.h
man/flame.1.md

Change `tcptls` to `dot` (but still accept `tcptls` on commandline for backwards compatibility). Require min libuv (fixes #29). Bump version.

Change "tcptls" to "dot"

---

3rd/json/json.hpp

Potential fix for https://github.com/DNS-OARC/flamethrower/issues/34 -
newer versions of json.hpp appear to support back to gcc 4.8.5.
json is only used for metrics output, so this was tested by running a
clean build and `./flame -o out.json 127.0.0.1`

upgrade json.hpp from v3.1.2 to v3.7.3

---

Dockerfile

19.04 is out of support and will no longer build.
Also, don't block docker build on interactively setting tzdata.

switch from ubuntu 19.04 to 20.04

---

flame/query.cpp

Related to openbsd support in https://github.com/DNS-OARC/flamethrower/issues/44

add missing include

---

man/flame.1
man/flame.1.md

This documents what happens if you set the batch count (`-q` setting) too high when using DoH. In the future, it might be better to directly report to the user when the batch count is too high (on top of only documenting it).

DoH: Document maximum concurrent streams for batch count

---

flame/main.cpp
flame/tokenbucket.h

Address same issue as #51 
```
√ cmake-build-debug % ./flame -Q 15000 localhost                                                                                                                                                         (rate-limit-precision)flamethrower
binding to 0.0.0.0
flaming target(s) [127.0.0.1] on port 53 with 10 concurrent generators, each sending 10 queries every 1ms on protocol udp
query generator [static] contains 1 record(s)
rate limit @ 15000 QPS (1500 QPS per concurrent sender)
0.931194s: send: 13950, avg send: 13950, recv: 0, avg recv: 0, min/avg/max resp: 0/nan/0ms, in flight: 13940, timeouts: 0
1.93186s: send: 15000, avg send: 14475, recv: 0, avg recv: 0, min/avg/max resp: 0/nan/0ms, in flight: 28940, timeouts: 0
2.93364s: send: 15000, avg send: 14650, recv: …
```

adjust token precision to double to fix rate limit precision

---

flame/metrics.cpp
flame/trafgen.cpp
flame/trafgen.h

I used this tool to run a test where I generated enough TCP connects to put all local ephemeral TCP ports into the TIME_WAIT state. The tool continued running, but all generators stopped sending queries, reporting "sent: 0" queries on periodic updates.
This change allows flamethrower to recover if ephemeral ports become available, and also reports out what error has occurred.

Handle Binding Errors

---

flame/trafgen.cpp

Previously, the value was ignored and set to 50ms.

Make the tcp-based modes honor the -d option.

---

flame/httpssession.cpp

This MR increases the size of a temporary receive buffer to hold
16K - exactly one max sized TLS record. This small change ensures
flamethrower compatibility with servers employing write request
buffering (consolidation) and deployments where TLS encryption is
offloaded to third-party software (e.g. haproxy). In the latter case,
the software could employ its own write buffering technics.
I managed to hit both of these use cases. In such a case, one would see
a lot of "malformed data" messages from the flamethrower.

DoH: increase temp. receive buffer size to 16K (#1)

---

CMakeLists.txt

Try to find catch2 package using pkg-config. Use system header if recent
enough. Fallback to bundled header otherwise.
Related to already fixed issue in catch header https://github.com/catchorg/Catch2/issues/2178

Use system catch headers if possible

---

CMakeLists.txt
README.md
flame/httpssession.h
flame/main.cpp
flame/target.h

Make docopt.cpp detect system package and use it if available. Use bundled library if not present.
Because url_parser seems to be just stripped http_parser, allow linking against that library. It seems to be far better maintained and is already packaged for Fedora distribution. Require manual override because it is (somehow) different library to use it.

3rd shared libraries

---

flame/httpssession.cpp
flame/httpssession.h
flame/trafgen.cpp
flame/trafgen.h

When running DoT or DoH with a low delay on a fast network, a race conditon appears that results in flamethrower livelocking.
The second commit fix a doh issue found while testing the first commit.

Fix issues when running with a low delay (-d option)

---

3rd/catch/catch2/catch.hpp

The existing code depended on the processor being x86_64.
Newer Macs are M1 (arm64)  based machines.
Fallback to using raise() when on a M1.

Add support to build on MacOS with M1 cpus.

---

CMakeLists.txt

It does not work on EPEL8 with gcc-8.4.1 current way, but works just
fine on Fedora's gcc-11.2.1.  flame/query.cpp uses base64_encode and
thus needs it also in flamecore already.
Without this change building of tests fails with:
``libflamecore.so: undefined reference to `base64_encode[abi:cxx11](unsigned char const*, unsigned int)'``
Sample of [failed build on EPEL8](https://kojipkgs.fedoraproject.org//work/tasks/2277/75892277/build.log).

Move base64 to flamecore

---

flame/query.cpp

Add missing includes to query.cpp. It does not compile anymore on gcc 12
without it.

Compile under gcc 12.0.0

---

flame/httpssession.cpp
flame/tcpsession.cpp

Responses received over UDP are limited to 512 bytes (without EDNS) but TCP, DoT and DoH ones are only limited to 2^16-1 (65535) bytes.
Without this fix flamethrower reports large responses as timeouts, which seems completely wrong.

TCP, DoT, DoH: Properly handle large responses
